defaults:
  - override hydra/job_logging: default

files:
  data_path: /data0/zijian/data/Aespa_data/exp_npy
  #k_space: /data0/zijian/data/Aespa_data/fmknee_pd_npy
  #coil_map: /path/to/coil_map
  #mask: /path/to/mask
  subject: ""
  slice: ""
paths:
  save_folder: ./result_exp

models:
  model: joint_training 
        
hyper_params: 
  gpu: '3'
  epochs: 2000
  lr: 5e-4
  aksmlr: 5e-5

params:
  real: 1 #real 0 : simulation, real 1 :raw
  reduction_factor: 4 # accel
  acs: 28
  center_fraction: 0.09 # (rf4, 0.09) (rf8, 0.05) in brain, image shape (640, 320)
  mask: 'uniform1d'
  crop_img_size: 320
  cutoff_low_freq: 0.8
  cutoff_high_freq: 200
  kspace_masking : 2800000
  selective_top_k : 200
  csm_update_iteration : 10